### ISSUE TITLE
Scrap 

### ISSUE THREAD

**Issue by Mgdj88** [Homelow1/pay-me-#11]
```
name: Staging CI

on:
  push:
    branches: [staging]
  workflow_dispatch:

jobs:
  buildAndDeploy:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        persist-credentials: false

    # Setup SSH and Submodules
    - name: Add SSH private keys for submodule repositories
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.OATUTOR_CONTENT_DEPLOY_KEY }}

    - name: Update submodules
      run: git submodule update --init --recursive

    # Save Git Author Information
    - name: Save original git author and git email
      run: |
        echo "git_email=$(git log --format='%ae' HEAD^!)" >> $GITHUB_ENV
        echo "git_name=$(git log --format='%an' HEAD^!)" >> $GITHUB_ENV

    # Setup Node.js Environment
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # Specify the Node.js version

    # Modify Project Configuration
    - name: Change homepage in package.json
      run: sed -i 's/place-holder/OATutor-Staging/g' package.json

    # Cache Dependencies
    - name: Cache node modules
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-

    # Install Dependencies
    - name: Install dependencies
      run: npm ci

    # Build the Project
    - name: Build project
      run: npm run build
      env:
        REACT_APP_FIREBASE_CONFIG: ${{ secrets.STAGING_FIREBASE_CONFIG }}
        CI: false
        REACT_APP_BUILD_TYPE: "platform-staging"
        REACT_APP_MIDDLEWARE_URL: ${{ secrets.STAGING_MIDDLEWARE_URL }}
        REACT_APP_COMMIT_HASH: ${{ github.sha }}

    # Checkout Staging Build Repository
    - name: Checkout staging build repository
      uses: actions/checkout@v3
      with:
        repository: 'CAHLR/OATutor-Staging'
        ssh-key: ${{ secrets.STAGING_SSH_PRIVATE_KEY }}
        ref: 'main'
        path: 'staging-build'

    # Deploy Changes
    - name: Deploy changes
      run: |
        cd staging-build
        git rm -rf .
        git clean -fxd
        rsync -av ../build/ .
        git add .
        git config --local user.email "${{ env.git_email }}"
        git config --local user.name "${{ env.git_name }}"
        git diff --cached --quiet --exit-code && echo "no changes to platform, exiting early" && exit 0
        git commit -m "deploy commit: CAHLR/OATutor@$GITHUB_SHA"
        git push
```
